// Source: https://raw.githubusercontent.com/DataDog/agent-payload/f0521943f60221829c6bb5de1c7f788cd4411372/agent_payload.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: agent_payload.proto

package model

import (
	_ "github.com/gogo/protobuf/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommonMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentVersion string  `protobuf:"bytes,1,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Timezone     string  `protobuf:"bytes,2,opt,name=timezone,proto3" json:"timezone,omitempty"`
	CurrentEpoch float64 `protobuf:"fixed64,3,opt,name=current_epoch,json=currentEpoch,proto3" json:"current_epoch,omitempty"`
	InternalIp   string  `protobuf:"bytes,4,opt,name=internal_ip,json=internalIp,proto3" json:"internal_ip,omitempty"`
	PublicIp     string  `protobuf:"bytes,5,opt,name=public_ip,json=publicIp,proto3" json:"public_ip,omitempty"`
	ApiKey       string  `protobuf:"bytes,6,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
}

func (x *CommonMetadata) Reset() {
	*x = CommonMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_payload_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonMetadata) ProtoMessage() {}

func (x *CommonMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_agent_payload_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonMetadata.ProtoReflect.Descriptor instead.
func (*CommonMetadata) Descriptor() ([]byte, []int) {
	return file_agent_payload_proto_rawDescGZIP(), []int{0}
}

func (x *CommonMetadata) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *CommonMetadata) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *CommonMetadata) GetCurrentEpoch() float64 {
	if x != nil {
		return x.CurrentEpoch
	}
	return 0
}

func (x *CommonMetadata) GetInternalIp() string {
	if x != nil {
		return x.InternalIp
	}
	return ""
}

func (x *CommonMetadata) GetPublicIp() string {
	if x != nil {
		return x.PublicIp
	}
	return ""
}

func (x *CommonMetadata) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type MetricsPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Samples  []*MetricsPayload_Sample `protobuf:"bytes,1,rep,name=samples,proto3" json:"samples,omitempty"`
	Metadata *CommonMetadata          `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *MetricsPayload) Reset() {
	*x = MetricsPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_payload_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetricsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsPayload) ProtoMessage() {}

func (x *MetricsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agent_payload_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsPayload.ProtoReflect.Descriptor instead.
func (*MetricsPayload) Descriptor() ([]byte, []int) {
	return file_agent_payload_proto_rawDescGZIP(), []int{1}
}

func (x *MetricsPayload) GetSamples() []*MetricsPayload_Sample {
	if x != nil {
		return x.Samples
	}
	return nil
}

func (x *MetricsPayload) GetMetadata() *CommonMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ServiceChecksPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceChecks []*ServiceChecksPayload_ServiceCheck `protobuf:"bytes,1,rep,name=service_checks,json=serviceChecks,proto3" json:"service_checks,omitempty"`
	Metadata      *CommonMetadata                      `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *ServiceChecksPayload) Reset() {
	*x = ServiceChecksPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_payload_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceChecksPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceChecksPayload) ProtoMessage() {}

func (x *ServiceChecksPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agent_payload_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceChecksPayload.ProtoReflect.Descriptor instead.
func (*ServiceChecksPayload) Descriptor() ([]byte, []int) {
	return file_agent_payload_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceChecksPayload) GetServiceChecks() []*ServiceChecksPayload_ServiceCheck {
	if x != nil {
		return x.ServiceChecks
	}
	return nil
}

func (x *ServiceChecksPayload) GetMetadata() *CommonMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type EventsPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events   []*EventsPayload_Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Metadata *CommonMetadata        `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *EventsPayload) Reset() {
	*x = EventsPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_payload_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsPayload) ProtoMessage() {}

func (x *EventsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agent_payload_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsPayload.ProtoReflect.Descriptor instead.
func (*EventsPayload) Descriptor() ([]byte, []int) {
	return file_agent_payload_proto_rawDescGZIP(), []int{3}
}

func (x *EventsPayload) GetEvents() []*EventsPayload_Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *EventsPayload) GetMetadata() *CommonMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SketchPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sketches []*SketchPayload_Sketch `protobuf:"bytes,1,rep,name=sketches,proto3" json:"sketches,omitempty"`
	Metadata *CommonMetadata         `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *SketchPayload) Reset() {
	*x = SketchPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_payload_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SketchPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SketchPayload) ProtoMessage() {}

func (x *SketchPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agent_payload_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SketchPayload.ProtoReflect.Descriptor instead.
func (*SketchPayload) Descriptor() ([]byte, []int) {
	return file_agent_payload_proto_rawDescGZIP(), []int{4}
}

func (x *SketchPayload) GetSketches() []*SketchPayload_Sketch {
	if x != nil {
		return x.Sketches
	}
	return nil
}

func (x *SketchPayload) GetMetadata() *CommonMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type HostMetadataPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostsMetadata []*HostMetadataPayload_HostMetadata `protobuf:"bytes,1,rep,name=hosts_metadata,json=hostsMetadata,proto3" json:"hosts_metadata,omitempty"`
	Metadata      *CommonMetadata                     `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *HostMetadataPayload) Reset() {
	*x = HostMetadataPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_payload_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostMetadataPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostMetadataPayload) ProtoMessage() {}

func (x *HostMetadataPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agent_payload_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostMetadataPayload.ProtoReflect.Descriptor instead.
func (*HostMetadataPayload) Descriptor() ([]byte, []int) {
	return file_agent_payload_proto_rawDescGZIP(), []int{5}
}

func (x *HostMetadataPayload) GetHostsMetadata() []*HostMetadataPayload_HostMetadata {
	if x != nil {
		return x.HostsMetadata
	}
	return nil
}

func (x *HostMetadataPayload) GetMetadata() *CommonMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type KubeMetadataPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deployments []*KubeMetadataPayload_Deployment `protobuf:"bytes,1,rep,name=deployments,proto3" json:"deployments,omitempty"`
	ReplicaSets []*KubeMetadataPayload_ReplicaSet `protobuf:"bytes,2,rep,name=replica_sets,json=replicaSets,proto3" json:"replica_sets,omitempty"`
	DaemonSets  []*KubeMetadataPayload_DaemonSet  `protobuf:"bytes,3,rep,name=daemon_sets,json=daemonSets,proto3" json:"daemon_sets,omitempty"`
	Services    []*KubeMetadataPayload_Service    `protobuf:"bytes,4,rep,name=services,proto3" json:"services,omitempty"`
	Jobs        []*KubeMetadataPayload_Job        `protobuf:"bytes,5,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Pods        []*KubeMetadataPayload_Pod        `protobuf:"bytes,6,rep,name=pods,proto3" json:"pods,omitempty"`
	Containers  []*KubeMetadataPayload_Container  `protobuf:"bytes,7,rep,name=containers,proto3" json:"containers,omitempty"`
}

func (x *KubeMetadataPayload) Reset() {
	*x = KubeMetadataPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_payload_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KubeMetadataPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeMetadataPayload) ProtoMessage() {}

func (x *KubeMetadataPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agent_payload_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubeMetadataPayload.ProtoReflect.Descriptor instead.
func (*KubeMetadataPayload) Descriptor() ([]byte, []int) {
	return file_agent_payload_proto_rawDescGZIP(), []int{6}
}

func (x *KubeMetadataPayload) GetDeployments() []*KubeMetadataPayload_Deployment {
	if x != nil {
		return x.Deployments
	}
	return nil
}

func (x *KubeMetadataPayload) GetReplicaSets() []*KubeMetadataPayload_ReplicaSet {
	if x != nil {
		return x.ReplicaSets
	}
	return nil
}

func (x *KubeMetadataPayload) GetDaemonSets() []*KubeMetadataPayload_DaemonSet {
	if x != nil {
		return x.DaemonSets
	}
	return nil
}

func (x *KubeMetadataPayload) GetServices() []*KubeMetadataPayload_Service {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *KubeMetadataPayload) GetJobs() []*KubeMetadataPayload_Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *KubeMetadataPayload) GetPods() []*KubeMetadataPayload_Pod {
	if x != nil {
		return x.Pods
	}
	return nil
}

func (x *KubeMetadataPayload) GetContainers() []*KubeMetadataPayload_Container {
	if x != nil {
		return x.Containers
	}
	return nil
}

type ECSMetadataPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tasks []*ECSMetadataPayload_Task `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
}

func (x *ECSMetadataPayload) Reset() {
	*x = ECSMetadataPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_payload_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECSMetadataPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECSMetadataPayload) ProtoMessage() {}

func (x *ECSMetadataPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agent_payload_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECSMetadataPayload.ProtoReflect.Descriptor instead.
func (*ECSMetadataPayload) Descriptor() ([]byte, []int) {
	return file_agent_payload_proto_rawDescGZIP(), []int{7}
}

func (x *ECSMetadataPayload) GetTasks() []*ECSMetadataPayload_Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type MetricsPayload_Sample struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metric         string                         `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Type           string                         `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Host           string                         `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Points         []*MetricsPayload_Sample_Point `protobuf:"bytes,4,rep,name=points,proto3" json:"points,omitempty"`
	Tags           []string                       `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	SourceTypeName string                         `protobuf:"bytes,6,opt,name=source_type_name,json=sourceTypeName,proto3" json:"source_type_name,omitempty"`
}

func (x *MetricsPayload_Sample) Reset() {
	*x = MetricsPayload_Sample{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_payload_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetricsPayload_Sample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsPayload_Sample) ProtoMessage() {}

func (x *MetricsPayload_Sample) ProtoReflect() protoreflect.Message {
	mi := &file_agent_payload_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsPayload_Sample.ProtoReflect.Descriptor instead.
func (*MetricsPayload_Sample) Descriptor() ([]byte, []int) {
	return file_agent_payload_proto_rawDescGZIP(), []int{1, 0}
}

func (x *MetricsPayload_Sample) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *MetricsPayload_Sample) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MetricsPayload_Sample) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *MetricsPayload_Sample) GetPoints() []*MetricsPayload_Sample_Point {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *MetricsPayload_Sample) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *MetricsPayload_Sample) GetSourceTypeName() string {
	if x != nil {
		return x.SourceTypeName
	}
	return ""
}

type MetricsPayload_Sample_Point struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts    int64   `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Value float64 `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *MetricsPayload_Sample_Point) Reset() {
	*x = MetricsPayload_Sample_Point{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_payload_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetricsPayload_Sample_Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsPayload_Sample_Point) ProtoMessage() {}

func (x *MetricsPayload_Sample_Point) ProtoReflect() protoreflect.Message {
	mi := &file_agent_payload_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsPayload_Sample_Point.ProtoReflect.Descriptor instead.
func (*MetricsPayload_Sample_Point) Descriptor() ([]byte, []int) {
	return file_agent_payload_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *MetricsPayload_Sample_Point) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *MetricsPayload_Sample_Point) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type ServiceChecksPayload_ServiceCheck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Host    string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Ts      int64    `protobuf:"varint,3,opt,name=ts,proto3" json:"ts,omitempty"`
	Status  int32    `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Message string   `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Tags    []string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *ServiceChecksPayload_ServiceCheck) Reset() {
	*x = ServiceChecksPayload_ServiceCheck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_payload_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceChecksPayload_ServiceCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceChecksPayload_ServiceCheck) ProtoMessage() {}

func (x *ServiceChecksPayload_ServiceCheck) ProtoReflect() protoreflect.Message {
	mi := &file_agent_payload_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceChecksPayload_ServiceCheck.ProtoReflect.Descriptor instead.
func (*ServiceChecksPayload_ServiceCheck) Descriptor() ([]byte, []int) {
	return file_agent_payload_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ServiceChecksPayload_ServiceCheck) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceChecksPayload_ServiceCheck) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ServiceChecksPayload_ServiceCheck) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *ServiceChecksPayload_ServiceCheck) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ServiceChecksPayload_ServiceCheck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ServiceChecksPayload_ServiceCheck) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type EventsPayload_Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title          string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Text           string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Ts             int64    `protobuf:"varint,3,opt,name=ts,proto3" json:"ts,omitempty"`
	Priority       string   `protobuf:"bytes,4,opt,name=priority,proto3" json:"priority,omitempty"`
	Host           string   `protobuf:"bytes,5,opt,name=host,proto3" json:"host,omitempty"`
	Tags           []string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	AlertType      string   `protobuf:"bytes,7,opt,name=alert_type,json=alertType,proto3" json:"alert_type,omitempty"`
	AggregationKey string   `protobuf:"bytes,8,opt,name=aggregation_key,json=aggregationKey,proto3" json:"aggregation_key,omitempty"`
	SourceTypeName string   `protobuf:"bytes,9,opt,name=source_type_name,json=sourceTypeName,proto3" json:"source_type_name,omitempty"`
}

func (x *EventsPayload_Event) Reset() {
	*x = EventsPayload_Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_payload_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventsPayload_Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsPayload_Event) ProtoMessage() {}

func (x *EventsPayload_Event) ProtoReflect() protoreflect.Message {
	mi := &file_agent_payload_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsPayload_Event.ProtoReflect.Descriptor instead.
func (*EventsPayload_Event) Descriptor() ([]byte, []int) {
	return file_agent_payload_proto_rawDescGZIP(), []int{3, 0}
}

func (x *EventsPayload_Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EventsPayload_Event) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *EventsPayload_Event) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *EventsPayload_Event) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *EventsPayload_Event) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *EventsPayload_Event) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *EventsPayload_Event) GetAlertType() string {
	if x != nil {
		return x.AlertType
	}
	return ""
}

func (x *EventsPayload_Event) GetAggregationKey() string {
	if x != nil {
		return x.AggregationKey
	}
	return ""
}

func (x *EventsPayload_Event) GetSourceTypeName() string {
	if x != nil {
		return x.SourceTypeName
	}
	return ""
}

type SketchPayload_Sketch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metric        string                               `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Host          string                               `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Distributions []*SketchPayload_Sketch_Distribution `protobuf:"bytes,3,rep,name=distributions,proto3" json:"distributions,omitempty"`
	Tags          []string                             `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Dogsketches   []*SketchPayload_Sketch_Dogsketch    `protobuf:"bytes,7,rep,name=dogsketches,proto3" json:"dogsketches,omitempty"`
}

func (x *SketchPayload_Sketch) Reset() {
	*x = SketchPayload_Sketch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_payload_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SketchPayload_Sketch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SketchPayload_Sketch) ProtoMessage() {}

func (x *SketchPayload_Sketch) ProtoReflect() protoreflect.Message {
	mi := &file_agent_payload_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SketchPayload_Sketch.ProtoReflect.Descriptor instead.
func (*SketchPayload_Sketch) Descriptor() ([]byte, []int) {
	return file_agent_payload_proto_rawDescGZIP(), []int{4, 0}
}

func (x *SketchPayload_Sketch) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *SketchPayload_Sketch) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *SketchPayload_Sketch) GetDistributions() []*SketchPayload_Sketch_Distribution {
	if x != nil {
		return x.Distributions
	}
	return nil
}

func (x *SketchPayload_Sketch) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SketchPayload_Sketch) GetDogsketches() []*SketchPayload_Sketch_Dogsketch {
	if x != nil {
		return x.Dogsketches
	}
	return nil
}

type SketchPayload_Sketch_Distribution struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts    int64     `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Cnt   int64     `protobuf:"varint,2,opt,name=cnt,proto3" json:"cnt,omitempty"`
	Min   float64   `protobuf:"fixed64,3,opt,name=min,proto3" json:"min,omitempty"`
	Max   float64   `protobuf:"fixed64,4,opt,name=max,proto3" json:"max,omitempty"`
	Avg   float64   `protobuf:"fixed64,5,opt,name=avg,proto3" json:"avg,omitempty"`
	Sum   float64   `protobuf:"fixed64,6,opt,name=sum,proto3" json:"sum,omitempty"`
	V     []float64 `protobuf:"fixed64,7,rep,packed,name=v,proto3" json:"v,omitempty"`
	G     []uint32  `protobuf:"varint,8,rep,packed,name=g,proto3" json:"g,omitempty"`
	Delta []uint32  `protobuf:"varint,9,rep,packed,name=delta,proto3" json:"delta,omitempty"`
	Buf   []float64 `protobuf:"fixed64,10,rep,packed,name=buf,proto3" json:"buf,omitempty"`
}

func (x *SketchPayload_Sketch_Distribution) Reset() {
	*x = SketchPayload_Sketch_Distribution{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_payload_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SketchPayload_Sketch_Distribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SketchPayload_Sketch_Distribution) ProtoMessage() {}

func (x *SketchPayload_Sketch_Distribution) ProtoReflect() protoreflect.Message {
	mi := &file_agent_payload_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SketchPayload_Sketch_Distribution.ProtoReflect.Descriptor instead.
func (*SketchPayload_Sketch_Distribution) Descriptor() ([]byte, []int) {
	return file_agent_payload_proto_rawDescGZIP(), []int{4, 0, 0}
}

func (x *SketchPayload_Sketch_Distribution) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *SketchPayload_Sketch_Distribution) GetCnt() int64 {
	if x != nil {
		return x.Cnt
	}
	return 0
}

func (x *SketchPayload_Sketch_Distribution) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *SketchPayload_Sketch_Distribution) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *SketchPayload_Sketch_Distribution) GetAvg() float64 {
	if x != nil {
		return x.Avg
	}
	return 0
}

func (x *SketchPayload_Sketch_Distribution) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *SketchPayload_Sketch_Distribution) GetV() []float64 {
	if x != nil {
		return x.V
	}
	return nil
}

func (x *SketchPayload_Sketch_Distribution) GetG() []uint32 {
	if x != nil {
		return x.G
	}
	return nil
}

func (x *SketchPayload_Sketch_Distribution) GetDelta() []uint32 {
	if x != nil {
		return x.Delta
	}
	return nil
}

func (x *SketchPayload_Sketch_Distribution) GetBuf() []float64 {
	if x != nil {
		return x.Buf
	}
	return nil
}

type SketchPayload_Sketch_Dogsketch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts  int64    `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Cnt int64    `protobuf:"varint,2,opt,name=cnt,proto3" json:"cnt,omitempty"`
	Min float64  `protobuf:"fixed64,3,opt,name=min,proto3" json:"min,omitempty"`
	Max float64  `protobuf:"fixed64,4,opt,name=max,proto3" json:"max,omitempty"`
	Avg float64  `protobuf:"fixed64,5,opt,name=avg,proto3" json:"avg,omitempty"`
	Sum float64  `protobuf:"fixed64,6,opt,name=sum,proto3" json:"sum,omitempty"`
	K   []int32  `protobuf:"zigzag32,7,rep,packed,name=k,proto3" json:"k,omitempty"`
	N   []uint32 `protobuf:"varint,8,rep,packed,name=n,proto3" json:"n,omitempty"`
}

func (x *SketchPayload_Sketch_Dogsketch) Reset() {
	*x = SketchPayload_Sketch_Dogsketch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_payload_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SketchPayload_Sketch_Dogsketch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SketchPayload_Sketch_Dogsketch) ProtoMessage() {}

func (x *SketchPayload_Sketch_Dogsketch) ProtoReflect() protoreflect.Message {
	mi := &file_agent_payload_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SketchPayload_Sketch_Dogsketch.ProtoReflect.Descriptor instead.
func (*SketchPayload_Sketch_Dogsketch) Descriptor() ([]byte, []int) {
	return file_agent_payload_proto_rawDescGZIP(), []int{4, 0, 1}
}

func (x *SketchPayload_Sketch_Dogsketch) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *SketchPayload_Sketch_Dogsketch) GetCnt() int64 {
	if x != nil {
		return x.Cnt
	}
	return 0
}

func (x *SketchPayload_Sketch_Dogsketch) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *SketchPayload_Sketch_Dogsketch) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *SketchPayload_Sketch_Dogsketch) GetAvg() float64 {
	if x != nil {
		return x.Avg
	}
	return 0
}

func (x *SketchPayload_Sketch_Dogsketch) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *SketchPayload_Sketch_Dogsketch) GetK() []int32 {
	if x != nil {
		return x.K
	}
	return nil
}

func (x *SketchPayload_Sketch_Dogsketch) GetN() []uint32 {
	if x != nil {
		return x.N
	}
	return nil
}

type HostMetadataPayload_TagSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Tags []string `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *HostMetadataPayload_TagSet) Reset() {
	*x = HostMetadataPayload_TagSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_payload_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostMetadataPayload_TagSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostMetadataPayload_TagSet) ProtoMessage() {}

func (x *HostMetadataPayload_TagSet) ProtoReflect() protoreflect.Message {
	mi := &file_agent_payload_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostMetadataPayload_TagSet.ProtoReflect.Descriptor instead.
func (*HostMetadataPayload_TagSet) Descriptor() ([]byte, []int) {
	return file_agent_payload_proto_rawDescGZIP(), []int{5, 0}
}

func (x *HostMetadataPayload_TagSet) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *HostMetadataPayload_TagSet) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type HostMetadataPayload_HostMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hostname string                        `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Tags     []*HostMetadataPayload_TagSet `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	Aliases  []string                      `protobuf:"bytes,3,rep,name=aliases,proto3" json:"aliases,omitempty"`
}

func (x *HostMetadataPayload_HostMetadata) Reset() {
	*x = HostMetadataPayload_HostMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_payload_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostMetadataPayload_HostMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostMetadataPayload_HostMetadata) ProtoMessage() {}

func (x *HostMetadataPayload_HostMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_agent_payload_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostMetadataPayload_HostMetadata.ProtoReflect.Descriptor instead.
func (*HostMetadataPayload_HostMetadata) Descriptor() ([]byte, []int) {
	return file_agent_payload_proto_rawDescGZIP(), []int{5, 1}
}

func (x *HostMetadataPayload_HostMetadata) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HostMetadataPayload_HostMetadata) GetTags() []*HostMetadataPayload_TagSet {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *HostMetadataPayload_HostMetadata) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

type KubeMetadataPayload_Deployment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid       string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *KubeMetadataPayload_Deployment) Reset() {
	*x = KubeMetadataPayload_Deployment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_payload_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KubeMetadataPayload_Deployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeMetadataPayload_Deployment) ProtoMessage() {}

func (x *KubeMetadataPayload_Deployment) ProtoReflect() protoreflect.Message {
	mi := &file_agent_payload_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubeMetadataPayload_Deployment.ProtoReflect.Descriptor instead.
func (*KubeMetadataPayload_Deployment) Descriptor() ([]byte, []int) {
	return file_agent_payload_proto_rawDescGZIP(), []int{6, 0}
}

func (x *KubeMetadataPayload_Deployment) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *KubeMetadataPayload_Deployment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KubeMetadataPayload_Deployment) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type KubeMetadataPayload_ReplicaSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid        string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace  string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Deployment string `protobuf:"bytes,4,opt,name=deployment,proto3" json:"deployment,omitempty"`
}

func (x *KubeMetadataPayload_ReplicaSet) Reset() {
	*x = KubeMetadataPayload_ReplicaSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_payload_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KubeMetadataPayload_ReplicaSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeMetadataPayload_ReplicaSet) ProtoMessage() {}

func (x *KubeMetadataPayload_ReplicaSet) ProtoReflect() protoreflect.Message {
	mi := &file_agent_payload_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubeMetadataPayload_ReplicaSet.ProtoReflect.Descriptor instead.
func (*KubeMetadataPayload_ReplicaSet) Descriptor() ([]byte, []int) {
	return file_agent_payload_proto_rawDescGZIP(), []int{6, 1}
}

func (x *KubeMetadataPayload_ReplicaSet) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *KubeMetadataPayload_ReplicaSet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KubeMetadataPayload_ReplicaSet) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *KubeMetadataPayload_ReplicaSet) GetDeployment() string {
	if x != nil {
		return x.Deployment
	}
	return ""
}

type KubeMetadataPayload_DaemonSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid       string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *KubeMetadataPayload_DaemonSet) Reset() {
	*x = KubeMetadataPayload_DaemonSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_payload_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KubeMetadataPayload_DaemonSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeMetadataPayload_DaemonSet) ProtoMessage() {}

func (x *KubeMetadataPayload_DaemonSet) ProtoReflect() protoreflect.Message {
	mi := &file_agent_payload_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubeMetadataPayload_DaemonSet.ProtoReflect.Descriptor instead.
func (*KubeMetadataPayload_DaemonSet) Descriptor() ([]byte, []int) {
	return file_agent_payload_proto_rawDescGZIP(), []int{6, 2}
}

func (x *KubeMetadataPayload_DaemonSet) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *KubeMetadataPayload_DaemonSet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KubeMetadataPayload_DaemonSet) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type KubeMetadataPayload_Service struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid       string            `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name      string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace string            `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Selector  map[string]string `protobuf:"bytes,4,rep,name=selector,proto3" json:"selector,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Type      string            `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *KubeMetadataPayload_Service) Reset() {
	*x = KubeMetadataPayload_Service{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_payload_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KubeMetadataPayload_Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeMetadataPayload_Service) ProtoMessage() {}

func (x *KubeMetadataPayload_Service) ProtoReflect() protoreflect.Message {
	mi := &file_agent_payload_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubeMetadataPayload_Service.ProtoReflect.Descriptor instead.
func (*KubeMetadataPayload_Service) Descriptor() ([]byte, []int) {
	return file_agent_payload_proto_rawDescGZIP(), []int{6, 3}
}

func (x *KubeMetadataPayload_Service) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *KubeMetadataPayload_Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KubeMetadataPayload_Service) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *KubeMetadataPayload_Service) GetSelector() map[string]string {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *KubeMetadataPayload_Service) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type KubeMetadataPayload_Job struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid       string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *KubeMetadataPayload_Job) Reset() {
	*x = KubeMetadataPayload_Job{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_payload_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KubeMetadataPayload_Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeMetadataPayload_Job) ProtoMessage() {}

func (x *KubeMetadataPayload_Job) ProtoReflect() protoreflect.Message {
	mi := &file_agent_payload_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubeMetadataPayload_Job.ProtoReflect.Descriptor instead.
func (*KubeMetadataPayload_Job) Descriptor() ([]byte, []int) {
	return file_agent_payload_proto_rawDescGZIP(), []int{6, 4}
}

func (x *KubeMetadataPayload_Job) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *KubeMetadataPayload_Job) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KubeMetadataPayload_Job) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type KubeMetadataPayload_Pod struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid                   string            `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                  string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace             string            `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	HostIp                string            `protobuf:"bytes,4,opt,name=host_ip,json=hostIp,proto3" json:"host_ip,omitempty"`
	PodIp                 string            `protobuf:"bytes,5,opt,name=pod_ip,json=podIp,proto3" json:"pod_ip,omitempty"`
	Labels                map[string]string `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ServiceUids           []string          `protobuf:"bytes,7,rep,name=service_uids,json=serviceUids,proto3" json:"service_uids,omitempty"`
	ContainerIds          []string          `protobuf:"bytes,8,rep,name=container_ids,json=containerIds,proto3" json:"container_ids,omitempty"`
	DaemonSet             string            `protobuf:"bytes,9,opt,name=daemon_set,json=daemonSet,proto3" json:"daemon_set,omitempty"`
	ReplicaSet            string            `protobuf:"bytes,10,opt,name=replica_set,json=replicaSet,proto3" json:"replica_set,omitempty"`
	ReplicationController string            `protobuf:"bytes,11,opt,name=replication_controller,json=replicationController,proto3" json:"replication_controller,omitempty"`
	Job                   string            `protobuf:"bytes,12,opt,name=job,proto3" json:"job,omitempty"`
}

func (x *KubeMetadataPayload_Pod) Reset() {
	*x = KubeMetadataPayload_Pod{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_payload_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KubeMetadataPayload_Pod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeMetadataPayload_Pod) ProtoMessage() {}

func (x *KubeMetadataPayload_Pod) ProtoReflect() protoreflect.Message {
	mi := &file_agent_payload_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubeMetadataPayload_Pod.ProtoReflect.Descriptor instead.
func (*KubeMetadataPayload_Pod) Descriptor() ([]byte, []int) {
	return file_agent_payload_proto_rawDescGZIP(), []int{6, 5}
}

func (x *KubeMetadataPayload_Pod) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *KubeMetadataPayload_Pod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KubeMetadataPayload_Pod) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *KubeMetadataPayload_Pod) GetHostIp() string {
	if x != nil {
		return x.HostIp
	}
	return ""
}

func (x *KubeMetadataPayload_Pod) GetPodIp() string {
	if x != nil {
		return x.PodIp
	}
	return ""
}

func (x *KubeMetadataPayload_Pod) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *KubeMetadataPayload_Pod) GetServiceUids() []string {
	if x != nil {
		return x.ServiceUids
	}
	return nil
}

func (x *KubeMetadataPayload_Pod) GetContainerIds() []string {
	if x != nil {
		return x.ContainerIds
	}
	return nil
}

func (x *KubeMetadataPayload_Pod) GetDaemonSet() string {
	if x != nil {
		return x.DaemonSet
	}
	return ""
}

func (x *KubeMetadataPayload_Pod) GetReplicaSet() string {
	if x != nil {
		return x.ReplicaSet
	}
	return ""
}

func (x *KubeMetadataPayload_Pod) GetReplicationController() string {
	if x != nil {
		return x.ReplicationController
	}
	return ""
}

func (x *KubeMetadataPayload_Pod) GetJob() string {
	if x != nil {
		return x.Job
	}
	return ""
}

type KubeMetadataPayload_Container struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image   string `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	ImageId string `protobuf:"bytes,4,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
}

func (x *KubeMetadataPayload_Container) Reset() {
	*x = KubeMetadataPayload_Container{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_payload_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KubeMetadataPayload_Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeMetadataPayload_Container) ProtoMessage() {}

func (x *KubeMetadataPayload_Container) ProtoReflect() protoreflect.Message {
	mi := &file_agent_payload_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubeMetadataPayload_Container.ProtoReflect.Descriptor instead.
func (*KubeMetadataPayload_Container) Descriptor() ([]byte, []int) {
	return file_agent_payload_proto_rawDescGZIP(), []int{6, 6}
}

func (x *KubeMetadataPayload_Container) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KubeMetadataPayload_Container) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KubeMetadataPayload_Container) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *KubeMetadataPayload_Container) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

type ECSMetadataPayload_Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Arn           string                          `protobuf:"bytes,1,opt,name=arn,proto3" json:"arn,omitempty"`
	DesiredStatus string                          `protobuf:"bytes,2,opt,name=desired_status,json=desiredStatus,proto3" json:"desired_status,omitempty"`
	KnownStatus   string                          `protobuf:"bytes,3,opt,name=known_status,json=knownStatus,proto3" json:"known_status,omitempty"`
	Family        string                          `protobuf:"bytes,4,opt,name=family,proto3" json:"family,omitempty"`
	Version       string                          `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Containers    []*ECSMetadataPayload_Container `protobuf:"bytes,6,rep,name=containers,proto3" json:"containers,omitempty"`
}

func (x *ECSMetadataPayload_Task) Reset() {
	*x = ECSMetadataPayload_Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_payload_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECSMetadataPayload_Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECSMetadataPayload_Task) ProtoMessage() {}

func (x *ECSMetadataPayload_Task) ProtoReflect() protoreflect.Message {
	mi := &file_agent_payload_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECSMetadataPayload_Task.ProtoReflect.Descriptor instead.
func (*ECSMetadataPayload_Task) Descriptor() ([]byte, []int) {
	return file_agent_payload_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ECSMetadataPayload_Task) GetArn() string {
	if x != nil {
		return x.Arn
	}
	return ""
}

func (x *ECSMetadataPayload_Task) GetDesiredStatus() string {
	if x != nil {
		return x.DesiredStatus
	}
	return ""
}

func (x *ECSMetadataPayload_Task) GetKnownStatus() string {
	if x != nil {
		return x.KnownStatus
	}
	return ""
}

func (x *ECSMetadataPayload_Task) GetFamily() string {
	if x != nil {
		return x.Family
	}
	return ""
}

func (x *ECSMetadataPayload_Task) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ECSMetadataPayload_Task) GetContainers() []*ECSMetadataPayload_Container {
	if x != nil {
		return x.Containers
	}
	return nil
}

type ECSMetadataPayload_Container struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DockerId   string `protobuf:"bytes,1,opt,name=docker_id,json=dockerId,proto3" json:"docker_id,omitempty"`
	DockerName string `protobuf:"bytes,2,opt,name=docker_name,json=dockerName,proto3" json:"docker_name,omitempty"`
	Name       string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ECSMetadataPayload_Container) Reset() {
	*x = ECSMetadataPayload_Container{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_payload_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECSMetadataPayload_Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECSMetadataPayload_Container) ProtoMessage() {}

func (x *ECSMetadataPayload_Container) ProtoReflect() protoreflect.Message {
	mi := &file_agent_payload_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECSMetadataPayload_Container.ProtoReflect.Descriptor instead.
func (*ECSMetadataPayload_Container) Descriptor() ([]byte, []int) {
	return file_agent_payload_proto_rawDescGZIP(), []int{7, 1}
}

func (x *ECSMetadataPayload_Container) GetDockerId() string {
	if x != nil {
		return x.DockerId
	}
	return ""
}

func (x *ECSMetadataPayload_Container) GetDockerName() string {
	if x != nil {
		return x.DockerName
	}
	return ""
}

func (x *ECSMetadataPayload_Container) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_agent_payload_proto protoreflect.FileDescriptor

var file_agent_payload_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x64, 0x61, 0x74, 0x61, 0x64, 0x6f, 0x67, 0x2e, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x1a, 0x2d, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x67, 0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xcd, 0x01, 0x0a, 0x0e, 0x43,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x23, 0x0a,
	0x0d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x12, 0x23,
	0x0a, 0x0d, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x45, 0x70,
	0x6f, 0x63, 0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f,
	0x69, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x49, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x69,
	0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49,
	0x70, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x70, 0x69, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x22, 0x9c, 0x03, 0x0a, 0x0e, 0x4d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x45, 0x0a,
	0x07, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x64, 0x6f, 0x67, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x07, 0x73, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x73, 0x12, 0x40, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x64, 0x6f, 0x67,
	0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x80, 0x02, 0x0a, 0x06, 0x53, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73,
	0x74, 0x12, 0x49, 0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x31, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x64, 0x6f, 0x67, 0x2e, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x61, 0x67, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73,
	0x12, 0x28, 0x0a, 0x10, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x2d, 0x0a, 0x05, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xc7, 0x02, 0x0a, 0x14, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x12, 0x5e, 0x0a, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x64, 0x6f, 0x67, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x52, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x73, 0x12, 0x40, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x64, 0x6f, 0x67, 0x2e, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x1a, 0x8c, 0x01, 0x0a, 0x0c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x61, 0x67, 0x73, 0x22, 0x8e, 0x03, 0x0a, 0x0d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x50, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x41, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x64, 0x6f, 0x67, 0x2e,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x40, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x64, 0x6f, 0x67, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x1a, 0xf7, 0x01, 0x0a, 0x05, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65,
	0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x73, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f,
	0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61,
	0x67, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x27, 0x0a, 0x0f, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x6b, 0x65, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x67, 0x67, 0x72,
	0x65, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x12, 0x28, 0x0a, 0x10, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0xb2, 0x06, 0x0a, 0x0d, 0x53, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x4c, 0x0a, 0x08, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x64,
	0x6f, 0x67, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e,
	0x53, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x53, 0x6b,
	0x65, 0x74, 0x63, 0x68, 0x42, 0x04, 0xc8, 0xde, 0x1f, 0x00, 0x52, 0x08, 0x73, 0x6b, 0x65, 0x74,
	0x63, 0x68, 0x65, 0x73, 0x12, 0x46, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x64, 0x6f, 0x67,
	0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x42, 0x04, 0xc8, 0xde,
	0x1f, 0x00, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x8a, 0x05, 0x0a,
	0x06, 0x53, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x12,
	0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68,
	0x6f, 0x73, 0x74, 0x12, 0x63, 0x0a, 0x0d, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x64, 0x6f, 0x67, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x2e, 0x53, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e,
	0x53, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x2e, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x42, 0x04, 0xc8, 0xde, 0x1f, 0x00, 0x52, 0x0d, 0x64, 0x69, 0x73, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x5c, 0x0a, 0x0b,
	0x64, 0x6f, 0x67, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x34, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x64, 0x6f, 0x67, 0x2e, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x53, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x53, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x2e, 0x44, 0x6f,
	0x67, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x42, 0x04, 0xc8, 0xde, 0x1f, 0x00, 0x52, 0x0b, 0x64,
	0x6f, 0x67, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x65, 0x73, 0x1a, 0xbc, 0x01, 0x0a, 0x0c, 0x44,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x63,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x63, 0x6e, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6d, 0x61,
	0x78, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x76, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03,
	0x61, 0x76, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x75, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x03, 0x73, 0x75, 0x6d, 0x12, 0x0c, 0x0a, 0x01, 0x76, 0x18, 0x07, 0x20, 0x03, 0x28, 0x01,
	0x52, 0x01, 0x76, 0x12, 0x0c, 0x0a, 0x01, 0x67, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x01,
	0x67, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0d,
	0x52, 0x05, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x75, 0x66, 0x18, 0x0a,
	0x20, 0x03, 0x28, 0x01, 0x52, 0x03, 0x62, 0x75, 0x66, 0x1a, 0x91, 0x01, 0x0a, 0x09, 0x44, 0x6f,
	0x67, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x63, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x61, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x12, 0x10, 0x0a,
	0x03, 0x61, 0x76, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x61, 0x76, 0x67, 0x12,
	0x10, 0x0a, 0x03, 0x73, 0x75, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x73, 0x75,
	0x6d, 0x12, 0x0c, 0x0a, 0x01, 0x6b, 0x18, 0x07, 0x20, 0x03, 0x28, 0x11, 0x52, 0x01, 0x6b, 0x12,
	0x0c, 0x0a, 0x01, 0x6e, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x01, 0x6e, 0x4a, 0x04, 0x08,
	0x05, 0x10, 0x06, 0x4a, 0x04, 0x08, 0x06, 0x10, 0x07, 0x52, 0x0e, 0x64, 0x69, 0x73, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x4b, 0x52, 0x0e, 0x64, 0x69, 0x73, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x43, 0x22, 0xf5, 0x02, 0x0a, 0x13, 0x48, 0x6f,
	0x73, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x12, 0x5d, 0x0a, 0x0e, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x64, 0x6f, 0x67, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x2e, 0x48, 0x6f, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x52, 0x0d, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x40, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x24, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x64, 0x6f, 0x67, 0x2e, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x1a, 0x30, 0x0a, 0x06, 0x54, 0x61, 0x67, 0x53, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x61, 0x67, 0x73, 0x1a, 0x8a, 0x01, 0x0a, 0x0c, 0x48, 0x6f, 0x73, 0x74, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x44, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x30, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x64, 0x6f, 0x67, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x54, 0x61, 0x67, 0x53, 0x65,
	0x74, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x6c, 0x69, 0x61, 0x73,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x65,
	0x73, 0x22, 0xe1, 0x0d, 0x0a, 0x13, 0x4b, 0x75, 0x62, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x56, 0x0a, 0x0b, 0x64, 0x65, 0x70,
	0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x34,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x64, 0x6f, 0x67, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x4b, 0x75, 0x62, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0b, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x12, 0x57, 0x0a, 0x0c, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x5f, 0x73, 0x65, 0x74,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x64, 0x6f,
	0x67, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x4b,
	0x75, 0x62, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x53, 0x65, 0x74, 0x52, 0x0b, 0x72,
	0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x53, 0x65, 0x74, 0x73, 0x12, 0x54, 0x0a, 0x0b, 0x64, 0x61,
	0x65, 0x6d, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x33, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x64, 0x6f, 0x67, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x4b, 0x75, 0x62, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x44, 0x61, 0x65, 0x6d, 0x6f,
	0x6e, 0x53, 0x65, 0x74, 0x52, 0x0a, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x73,
	0x12, 0x4d, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x31, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x64, 0x6f, 0x67, 0x2e, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x4b, 0x75, 0x62, 0x65, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12,
	0x41, 0x0a, 0x04, 0x6a, 0x6f, 0x62, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e,
	0x64, 0x61, 0x74, 0x61, 0x64, 0x6f, 0x67, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x4b, 0x75, 0x62, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x4a, 0x6f, 0x62, 0x52, 0x04, 0x6a, 0x6f,
	0x62, 0x73, 0x12, 0x41, 0x0a, 0x04, 0x70, 0x6f, 0x64, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x2d, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x64, 0x6f, 0x67, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x4b, 0x75, 0x62, 0x65, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x50, 0x6f, 0x64, 0x52,
	0x04, 0x70, 0x6f, 0x64, 0x73, 0x12, 0x53, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x64, 0x6f, 0x67, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x2e, 0x4b, 0x75, 0x62, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x52, 0x0a,
	0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x1a, 0x50, 0x0a, 0x0a, 0x44, 0x65,
	0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x1a, 0x70, 0x0a, 0x0a,
	0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x53, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x1a, 0x4f,
	0x0a, 0x09, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x1a,
	0xfb, 0x01, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12,
	0x5b, 0x0a, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x3f, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x64, 0x6f, 0x67, 0x2e, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x4b, 0x75, 0x62, 0x65, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x1a, 0x3b, 0x0a, 0x0d, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x49, 0x0a,
	0x03, 0x4a, 0x6f, 0x62, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61,
	0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x1a, 0xd8, 0x03, 0x0a, 0x03, 0x50, 0x6f, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x70, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x70, 0x12, 0x15, 0x0a,
	0x06, 0x70, 0x6f, 0x64, 0x5f, 0x69, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70,
	0x6f, 0x64, 0x49, 0x70, 0x12, 0x51, 0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x39, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x64, 0x6f, 0x67, 0x2e, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x4b, 0x75, 0x62, 0x65,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e,
	0x50, 0x6f, 0x64, 0x2e, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x5f, 0x75, 0x69, 0x64, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x55, 0x69, 0x64, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x73, 0x12,
	0x1d, 0x0a, 0x0a, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x74, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x12, 0x1f,
	0x0a, 0x0b, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x5f, 0x73, 0x65, 0x74, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x53, 0x65, 0x74, 0x12,
	0x35, 0x0a, 0x16, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x15, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6a, 0x6f, 0x62, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6a, 0x6f, 0x62, 0x1a, 0x39, 0x0a, 0x0b, 0x4c, 0x61, 0x62, 0x65,
	0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x1a, 0x60, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x49, 0x64, 0x22, 0xa3, 0x03, 0x0a, 0x12, 0x45, 0x43, 0x53, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x43, 0x0a, 0x05,
	0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x64, 0x61,
	0x74, 0x61, 0x64, 0x6f, 0x67, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x2e, 0x45, 0x43, 0x53, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x50, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x05, 0x74, 0x61, 0x73, 0x6b,
	0x73, 0x1a, 0xe8, 0x01, 0x0a, 0x04, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x72,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x72, 0x6e, 0x12, 0x25, 0x0a, 0x0e,
	0x64, 0x65, 0x73, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x64, 0x65, 0x73, 0x69, 0x72, 0x65, 0x64, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6b, 0x6e, 0x6f, 0x77, 0x6e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x52, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x64, 0x6f, 0x67, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x2e, 0x45, 0x43, 0x53, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72,
	0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x1a, 0x5d, 0x0a, 0x09,
	0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x6f, 0x63,
	0x6b, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x6f,
	0x63, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x6f, 0x63,
	0x6b, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x40, 0x5a, 0x3e, 0x67,
	0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x56,
	0x69, 0x73, 0x74, 0x61, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x2d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_agent_payload_proto_rawDescOnce sync.Once
	file_agent_payload_proto_rawDescData = file_agent_payload_proto_rawDesc
)

func file_agent_payload_proto_rawDescGZIP() []byte {
	file_agent_payload_proto_rawDescOnce.Do(func() {
		file_agent_payload_proto_rawDescData = protoimpl.X.CompressGZIP(file_agent_payload_proto_rawDescData)
	})
	return file_agent_payload_proto_rawDescData
}

var file_agent_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_agent_payload_proto_goTypes = []interface{}{
	(*CommonMetadata)(nil),                    // 0: datadog.agentpayload.CommonMetadata
	(*MetricsPayload)(nil),                    // 1: datadog.agentpayload.MetricsPayload
	(*ServiceChecksPayload)(nil),              // 2: datadog.agentpayload.ServiceChecksPayload
	(*EventsPayload)(nil),                     // 3: datadog.agentpayload.EventsPayload
	(*SketchPayload)(nil),                     // 4: datadog.agentpayload.SketchPayload
	(*HostMetadataPayload)(nil),               // 5: datadog.agentpayload.HostMetadataPayload
	(*KubeMetadataPayload)(nil),               // 6: datadog.agentpayload.KubeMetadataPayload
	(*ECSMetadataPayload)(nil),                // 7: datadog.agentpayload.ECSMetadataPayload
	(*MetricsPayload_Sample)(nil),             // 8: datadog.agentpayload.MetricsPayload.Sample
	(*MetricsPayload_Sample_Point)(nil),       // 9: datadog.agentpayload.MetricsPayload.Sample.Point
	(*ServiceChecksPayload_ServiceCheck)(nil), // 10: datadog.agentpayload.ServiceChecksPayload.ServiceCheck
	(*EventsPayload_Event)(nil),               // 11: datadog.agentpayload.EventsPayload.Event
	(*SketchPayload_Sketch)(nil),              // 12: datadog.agentpayload.SketchPayload.Sketch
	(*SketchPayload_Sketch_Distribution)(nil), // 13: datadog.agentpayload.SketchPayload.Sketch.Distribution
	(*SketchPayload_Sketch_Dogsketch)(nil),    // 14: datadog.agentpayload.SketchPayload.Sketch.Dogsketch
	(*HostMetadataPayload_TagSet)(nil),        // 15: datadog.agentpayload.HostMetadataPayload.TagSet
	(*HostMetadataPayload_HostMetadata)(nil),  // 16: datadog.agentpayload.HostMetadataPayload.HostMetadata
	(*KubeMetadataPayload_Deployment)(nil),    // 17: datadog.agentpayload.KubeMetadataPayload.Deployment
	(*KubeMetadataPayload_ReplicaSet)(nil),    // 18: datadog.agentpayload.KubeMetadataPayload.ReplicaSet
	(*KubeMetadataPayload_DaemonSet)(nil),     // 19: datadog.agentpayload.KubeMetadataPayload.DaemonSet
	(*KubeMetadataPayload_Service)(nil),       // 20: datadog.agentpayload.KubeMetadataPayload.Service
	(*KubeMetadataPayload_Job)(nil),           // 21: datadog.agentpayload.KubeMetadataPayload.Job
	(*KubeMetadataPayload_Pod)(nil),           // 22: datadog.agentpayload.KubeMetadataPayload.Pod
	(*KubeMetadataPayload_Container)(nil),     // 23: datadog.agentpayload.KubeMetadataPayload.Container
	nil,                                       // 24: datadog.agentpayload.KubeMetadataPayload.Service.SelectorEntry
	nil,                                       // 25: datadog.agentpayload.KubeMetadataPayload.Pod.LabelsEntry
	(*ECSMetadataPayload_Task)(nil),           // 26: datadog.agentpayload.ECSMetadataPayload.Task
	(*ECSMetadataPayload_Container)(nil),      // 27: datadog.agentpayload.ECSMetadataPayload.Container
}
var file_agent_payload_proto_depIdxs = []int32{
	8,  // 0: datadog.agentpayload.MetricsPayload.samples:type_name -> datadog.agentpayload.MetricsPayload.Sample
	0,  // 1: datadog.agentpayload.MetricsPayload.metadata:type_name -> datadog.agentpayload.CommonMetadata
	10, // 2: datadog.agentpayload.ServiceChecksPayload.service_checks:type_name -> datadog.agentpayload.ServiceChecksPayload.ServiceCheck
	0,  // 3: datadog.agentpayload.ServiceChecksPayload.metadata:type_name -> datadog.agentpayload.CommonMetadata
	11, // 4: datadog.agentpayload.EventsPayload.events:type_name -> datadog.agentpayload.EventsPayload.Event
	0,  // 5: datadog.agentpayload.EventsPayload.metadata:type_name -> datadog.agentpayload.CommonMetadata
	12, // 6: datadog.agentpayload.SketchPayload.sketches:type_name -> datadog.agentpayload.SketchPayload.Sketch
	0,  // 7: datadog.agentpayload.SketchPayload.metadata:type_name -> datadog.agentpayload.CommonMetadata
	16, // 8: datadog.agentpayload.HostMetadataPayload.hosts_metadata:type_name -> datadog.agentpayload.HostMetadataPayload.HostMetadata
	0,  // 9: datadog.agentpayload.HostMetadataPayload.metadata:type_name -> datadog.agentpayload.CommonMetadata
	17, // 10: datadog.agentpayload.KubeMetadataPayload.deployments:type_name -> datadog.agentpayload.KubeMetadataPayload.Deployment
	18, // 11: datadog.agentpayload.KubeMetadataPayload.replica_sets:type_name -> datadog.agentpayload.KubeMetadataPayload.ReplicaSet
	19, // 12: datadog.agentpayload.KubeMetadataPayload.daemon_sets:type_name -> datadog.agentpayload.KubeMetadataPayload.DaemonSet
	20, // 13: datadog.agentpayload.KubeMetadataPayload.services:type_name -> datadog.agentpayload.KubeMetadataPayload.Service
	21, // 14: datadog.agentpayload.KubeMetadataPayload.jobs:type_name -> datadog.agentpayload.KubeMetadataPayload.Job
	22, // 15: datadog.agentpayload.KubeMetadataPayload.pods:type_name -> datadog.agentpayload.KubeMetadataPayload.Pod
	23, // 16: datadog.agentpayload.KubeMetadataPayload.containers:type_name -> datadog.agentpayload.KubeMetadataPayload.Container
	26, // 17: datadog.agentpayload.ECSMetadataPayload.tasks:type_name -> datadog.agentpayload.ECSMetadataPayload.Task
	9,  // 18: datadog.agentpayload.MetricsPayload.Sample.points:type_name -> datadog.agentpayload.MetricsPayload.Sample.Point
	13, // 19: datadog.agentpayload.SketchPayload.Sketch.distributions:type_name -> datadog.agentpayload.SketchPayload.Sketch.Distribution
	14, // 20: datadog.agentpayload.SketchPayload.Sketch.dogsketches:type_name -> datadog.agentpayload.SketchPayload.Sketch.Dogsketch
	15, // 21: datadog.agentpayload.HostMetadataPayload.HostMetadata.tags:type_name -> datadog.agentpayload.HostMetadataPayload.TagSet
	24, // 22: datadog.agentpayload.KubeMetadataPayload.Service.selector:type_name -> datadog.agentpayload.KubeMetadataPayload.Service.SelectorEntry
	25, // 23: datadog.agentpayload.KubeMetadataPayload.Pod.labels:type_name -> datadog.agentpayload.KubeMetadataPayload.Pod.LabelsEntry
	27, // 24: datadog.agentpayload.ECSMetadataPayload.Task.containers:type_name -> datadog.agentpayload.ECSMetadataPayload.Container
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_agent_payload_proto_init() }
func file_agent_payload_proto_init() {
	if File_agent_payload_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_agent_payload_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_payload_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetricsPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_payload_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceChecksPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_payload_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventsPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_payload_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SketchPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_payload_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostMetadataPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_payload_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KubeMetadataPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_payload_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECSMetadataPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_payload_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetricsPayload_Sample); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_payload_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetricsPayload_Sample_Point); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_payload_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceChecksPayload_ServiceCheck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_payload_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventsPayload_Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_payload_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SketchPayload_Sketch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_payload_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SketchPayload_Sketch_Distribution); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_payload_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SketchPayload_Sketch_Dogsketch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_payload_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostMetadataPayload_TagSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_payload_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostMetadataPayload_HostMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_payload_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KubeMetadataPayload_Deployment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_payload_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KubeMetadataPayload_ReplicaSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_payload_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KubeMetadataPayload_DaemonSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_payload_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KubeMetadataPayload_Service); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_payload_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KubeMetadataPayload_Job); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_payload_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KubeMetadataPayload_Pod); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_payload_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KubeMetadataPayload_Container); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_payload_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECSMetadataPayload_Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_payload_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECSMetadataPayload_Container); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_agent_payload_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agent_payload_proto_goTypes,
		DependencyIndexes: file_agent_payload_proto_depIdxs,
		MessageInfos:      file_agent_payload_proto_msgTypes,
	}.Build()
	File_agent_payload_proto = out.File
	file_agent_payload_proto_rawDesc = nil
	file_agent_payload_proto_goTypes = nil
	file_agent_payload_proto_depIdxs = nil
}
